# Generated by Django 4.1.5 on 2023-04-04 14:58

from django.db import migrations


def correct_files_inspected_status(apps, schema_editor):
    """ Import initial data for ImportSchemeStatus and ImportSchemeFileStatus """

    ImportSchemeStatus = apps.get_model("ml_import_wizard", "ImportSchemeStatus")

    status = ImportSchemeStatus.objects.get(name="Files Inspected")
    status.import_defined = False
    status.save()


def reverse_func(apps, schema_editor):
    """ This isn't reversable """

    ...


class Migration(migrations.Migration):

    dependencies = [
        ('ml_import_wizard', '0002_initial_statuses'),
    ]

    operations = [
        migrations.RunPython(correct_files_inspected_status, reverse_func)
    ]
