# Generated by Django 4.1.5 on 2024-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_import_wizard", "0003_status_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="importscheme",
            name="process_created_time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="importscheme",
            name="process_pid",
            field=models.IntegerField(null=True),
        ),
    ]
