# Generated by Django 4.1.5 on 2023-04-04 14:58

from django.db import migrations


def load_initial_data(apps, schema_editor):
    """ Import initial data for ImportSchemeStatus and ImportSchemeFileStatus """

    ImportSchemeStatus = apps.get_model("ml_import_wizard", "ImportSchemeStatus")
    ImportSchemeFileStatus = apps.get_model("ml_import_wizard", "ImportSchemeFileStatus")

    scheme_statuses: list = [
        {"name": "Import Failed", "files_received": True, "files_inspected": True, "import_defined": True,"data_previewed": True, "import_started": True, "import_completed": False, "import_failed": True},

    ]

    for scheme_status in scheme_statuses:
        status = ImportSchemeStatus(**scheme_status)
        status.save()


def reverse_func(apps, schema_editor):
    """ Remove out statuses if a reverse is done """

    ImportSchemeStatus = apps.get_model("ml_import_wizard", "ImportSchemeStatus")

    ImportSchemeStatus.objects.filter(name="Import Failed").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ml_import_wizard', '0005_importschemestatus_import_failed'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
